/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as CamaraRouteImport } from './routes/camara'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DashboardsRouteImport } from './routes/dashboards'
import { Route as DouRouteImport } from './routes/dou'
import { Route as MonitoramentoRouteImport } from './routes/monitoramento'
import { Route as NovasProposicoesRouteImport } from './routes/novas-proposicoes'
import { Route as PerfisRouteImport } from './routes/perfis'
import { Route as SenadoRouteImport } from './routes/senado'
import { Route as TseRouteImport } from './routes/tse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const CamaraRoute = CamaraRouteImport.update({
  id: '/camara',
  path: '/camara',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRoute = DashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const DouRoute = DouRouteImport.update({
  id: '/dou',
  path: '/dou',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoramentoRoute = MonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => rootRouteImport,
} as any)
const NovasProposicoesRoute = NovasProposicoesRouteImport.update({
  id: '/novas-proposicoes',
  path: '/novas-proposicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfisRoute = PerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => rootRouteImport,
} as any)
const SenadoRoute = SenadoRouteImport.update({
  id: '/senado',
  path: '/senado',
  getParentRoute: () => rootRouteImport,
} as any)
const TseRoute = TseRouteImport.update({
  id: '/tse',
  path: '/tse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/camara': typeof CamaraRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboards': typeof DashboardsRoute
  '/dou': typeof DouRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/novas-proposicoes': typeof NovasProposicoesRoute
  '/perfis': typeof PerfisRoute
  '/senado': typeof SenadoRoute
  '/tse': typeof TseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/camara': typeof CamaraRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboards': typeof DashboardsRoute
  '/dou': typeof DouRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/novas-proposicoes': typeof NovasProposicoesRoute
  '/perfis': typeof PerfisRoute
  '/senado': typeof SenadoRoute
  '/tse': typeof TseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/camara': typeof CamaraRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboards': typeof DashboardsRoute
  '/dou': typeof DouRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/novas-proposicoes': typeof NovasProposicoesRoute
  '/perfis': typeof PerfisRoute
  '/senado': typeof SenadoRoute
  '/tse': typeof TseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ajuda'
    | '/camara'
    | '/configuracoes'
    | '/dashboards'
    | '/dou'
    | '/monitoramento'
    | '/novas-proposicoes'
    | '/perfis'
    | '/senado'
    | '/tse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ajuda'
    | '/camara'
    | '/configuracoes'
    | '/dashboards'
    | '/dou'
    | '/monitoramento'
    | '/novas-proposicoes'
    | '/perfis'
    | '/senado'
    | '/tse'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ajuda'
    | '/camara'
    | '/configuracoes'
    | '/dashboards'
    | '/dou'
    | '/monitoramento'
    | '/novas-proposicoes'
    | '/perfis'
    | '/senado'
    | '/tse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AjudaRoute: typeof AjudaRoute
  CamaraRoute: typeof CamaraRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardsRoute: typeof DashboardsRoute
  DouRoute: typeof DouRoute
  MonitoramentoRoute: typeof MonitoramentoRoute
  NovasProposicoesRoute: typeof NovasProposicoesRoute
  PerfisRoute: typeof PerfisRoute
  SenadoRoute: typeof SenadoRoute
  TseRoute: typeof TseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camara': {
      id: '/camara'
      path: '/camara'
      fullPath: '/camara'
      preLoaderRoute: typeof CamaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards': {
      id: '/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dou': {
      id: '/dou'
      path: '/dou'
      fullPath: '/dou'
      preLoaderRoute: typeof DouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoramento': {
      id: '/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof MonitoramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novas-proposicoes': {
      id: '/novas-proposicoes'
      path: '/novas-proposicoes'
      fullPath: '/novas-proposicoes'
      preLoaderRoute: typeof NovasProposicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfis': {
      id: '/perfis'
      path: '/perfis'
      fullPath: '/perfis'
      preLoaderRoute: typeof PerfisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senado': {
      id: '/senado'
      path: '/senado'
      fullPath: '/senado'
      preLoaderRoute: typeof SenadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tse': {
      id: '/tse'
      path: '/tse'
      fullPath: '/tse'
      preLoaderRoute: typeof TseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AjudaRoute: AjudaRoute,
  CamaraRoute: CamaraRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardsRoute: DashboardsRoute,
  DouRoute: DouRoute,
  MonitoramentoRoute: MonitoramentoRoute,
  NovasProposicoesRoute: NovasProposicoesRoute,
  PerfisRoute: PerfisRoute,
  SenadoRoute: SenadoRoute,
  TseRoute: TseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
